name: Build Debug APK

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Build type"
        required: true
        default: "debug"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK
        env:
          GRADLE_OPTS: -Xmx6g
        run: |
          if [ "${{ github.event.inputs.build_type }}" = "release" ]; then
            ./gradlew assembleRelease --no-daemon
          else
            ./gradlew assembleDebug --no-daemon
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/**/*.apk
